scrape_configs:
  - job_name: 'collector'
    scrape_interval: 1s
    static_configs:
      - targets: ['otel-collector:8888']
      - targets: ['otel-collector:8889']

  - job_name: 'jaeger'
    scrape_interval: 1s
    metrics_path: /metrics
    static_configs:
      - targets:
        - jaeger-all-in-one:14269
